/**
 * Bridge — Initialise the .factory folder in a target repo.
 *
 * The .factory folder is the structured contract between a repo and
 * the factory.  It contains:
 *   factory.yaml  — manifest (what the repo exposes)
 *   specs/apps/   — app spec YAMLs
 *   specs/features/ — feature spec YAMLs
 */

import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { stringify as toYaml, parse as parseYaml } from 'yaml';
import { ensureDir, writeFile, log } from './utils.ts';

// ─── Types ────────────────────────────────────────────────

export interface BridgeConfig {
    version: number;
    name: string;
    description: string;
    registry?: { apps?: string };
    conventions?: { rules?: string; agents?: string };
    skills?: Array<{ app: string; path: string }>;
    templates?: { starter?: string };
    apps_dir?: string;
}

// Files to look for when auto-discovering skills
const SKILL_FILENAMES = ['skills.md', 'SKILL.md', 'agents.md', 'AGENTS.md'];

// ─── Public API ───────────────────────────────────────────

/**
 * Initialise or refresh the .factory bridge in a target repo.
 * If factory.yaml already exists, it is preserved.  Otherwise one
 * is generated by scanning the repo.
 */
export function initBridge(repoPath: string): BridgeConfig {
    if (!existsSync(repoPath)) {
        throw new Error(`Repo not found: ${repoPath}`);
    }

    const factoryDir = join(repoPath, '.factory');
    const manifestPath = join(factoryDir, 'factory.yaml');

    // If manifest already exists, load and return it
    if (existsSync(manifestPath)) {
        log('●', '.factory/factory.yaml already exists — preserving');
        const config = loadBridgeConfig(repoPath);
        ensureDirectories(factoryDir);
        return config;
    }

    // Auto-discover and generate
    log('●', 'Scanning repo and creating .factory bridge...');
    const config = discoverBridgeConfig(repoPath);

    // Create structure
    ensureDir(factoryDir);
    ensureDirectories(factoryDir);

    // Write manifest
    writeFile(manifestPath, toYaml(config) + '\n');

    // Write agents.md — instructions for AI agents working in this folder
    writeAgentsMd(factoryDir, config.name);

    log('✓', `Bridge created at ${factoryDir}`);
    log('  ', `  Name: ${config.name}`);
    log('  ', `  Apps dir: ${config.apps_dir || 'apps'}`);
    log('  ', `  Skills: ${config.skills?.length || 0} files discovered`);

    return config;
}

/**
 * Load an existing factory.yaml from a repo.
 */
export function loadBridgeConfig(repoPath: string): BridgeConfig {
    const manifestPath = join(repoPath, '.factory', 'factory.yaml');
    if (!existsSync(manifestPath)) {
        throw new Error(`No .factory/factory.yaml found in ${repoPath}`);
    }
    return parseYaml(readFileSync(manifestPath, 'utf-8')) as BridgeConfig;
}

/**
 * Check whether a repo already has a .factory bridge.
 */
export function hasBridge(repoPath: string): boolean {
    return existsSync(join(repoPath, '.factory', 'factory.yaml'));
}

// ─── Internal ─────────────────────────────────────────────

function ensureDirectories(factoryDir: string): void {
    ensureDir(join(factoryDir, 'specs', 'apps'));
    ensureDir(join(factoryDir, 'specs', 'features'));
}

/**
 * Write an agents.md file that instructs AI agents how to create and
 * maintain documents inside this .factory folder.
 */
function writeAgentsMd(factoryDir: string, projectName: string): void {
    const agentsPath = join(factoryDir, 'agents.md');

    // Don't overwrite if it already exists (e.g. user customised it)
    if (existsSync(agentsPath)) return;

    const content = `# .factory — Agent Instructions

> This folder is the bridge between the **${projectName}** repo and the
> **SaveADay Factory** engine. Everything here is machine-readable.

## Folder Structure

\`\`\`
.factory/
├── factory.yaml          ← Manifest (auto-generated, do not delete)
├── agents.md             ← This file — agent instructions
└── specs/
    ├── apps/             ← App spec YAMLs
    └── features/         ← Feature spec YAMLs
\`\`\`

## factory.yaml

The manifest describes what this repo exposes to the factory. It is
auto-generated by \`factory init-bridge\`. You may edit it, but keep these
fields:

| Field          | Required | Purpose                                      |
| -------------- | -------- | -------------------------------------------- |
| \`version\`      | yes      | Schema version (currently \`1\`)                |
| \`name\`         | yes      | Human-readable project name                  |
| \`description\`  | no       | Short description of the project             |
| \`registry.apps\`| no       | Path to \`apps.json\` (app registry)            |
| \`conventions\`  | no       | Paths to rules and agent files               |
| \`skills\`       | no       | List of discovered skill/agent files per app |
| \`templates\`    | no       | Starter template path                        |
| \`apps_dir\`     | no       | Base directory for apps (default: \`apps\`)     |

## Writing App Specs (\`specs/apps/\`)

Each YAML file describes a **complete application** to generate.

### Naming

- Use **kebab-case**: \`my-app.yaml\`
- Prefix with \`_\` for templates/examples: \`_template.yaml\`
  (files starting with \`_\` are hidden from the UI)

### Required Structure

\`\`\`yaml
apiVersion: saveaday/v1
kind: AppSpec
status: draft              # draft | ready | in-progress | done

metadata:
  name: My App
  slug: my_app             # Unique, snake_case
  description: Short description
  icon: Sparkles           # Lucide icon name
  color: "#6366f1"
  group: superapp           # superapp | infrastructure | independent

deployment:
  port: 3020               # Unique port number
  region: us-central1

database:
  firestoreId: my-app
  collections: [items]

api:
  resources:
    - name: item
      collection: items
      fields:
        title: { type: string, required: true }
        status: { type: string, default: "active" }
\`\`\`

### Field Types

Allowed types: \`string\`, \`number\`, \`boolean\`, \`array\`, \`object\`.
Each field can have \`required\` (boolean) and \`default\` (any).

## Writing Feature Specs (\`specs/features/\`)

Each YAML file describes a **feature to add** to an existing app.

### Naming

Same conventions as app specs: kebab-case, \`_\` prefix for templates.

### Required Structure

\`\`\`yaml
apiVersion: saveaday/v1
kind: FeatureSpec
status: draft

target:
  app: my_app              # slug of the target app

feature:
  name: My Feature
  slug: my-feature
  description: What this feature does

model:
  name: MyModel
  collection: myModels
  fields:
    title: { type: string, required: true }

pages:
  - route: /my-feature
    title: My Feature
    type: list              # list | form | detail | custom
\`\`\`

## Rules for Agents

1. **Never delete or rename** \`factory.yaml\` — the engine depends on it.
2. **One spec per file.** Do not combine multiple apps or features.
3. **Validate before committing.** Run \`factory validate <file>\` to check.
4. **Keep slugs unique** across all specs in the project.
5. **Use the engine pipeline** — do not hand-write generated output.
6. **Ports must be unique** — check \`apps.json\` (if present) before picking.
`;

    writeFile(agentsPath, content);
    log('  ', '  ✓ Generated agents.md');
}

/**
 * Scan a repo and build a BridgeConfig by auto-discovering known files.
 */
function discoverBridgeConfig(repoPath: string): BridgeConfig {
    const config: BridgeConfig = {
        version: 1,
        name: guessRepoName(repoPath),
        description: '',
    };

    // 1. Registry — look for apps.json
    if (existsSync(join(repoPath, 'apps.json'))) {
        config.registry = { apps: 'apps.json' };
        log('  ', '  ✓ Found apps.json');
    }

    // 2. Conventions — look for .agent/rules/ and AGENTS.md
    const rulesDir = join(repoPath, '.agent', 'rules');
    const agentsFile = join(repoPath, 'AGENTS.md');
    if (existsSync(rulesDir) || existsSync(agentsFile)) {
        config.conventions = {};
        if (existsSync(rulesDir)) {
            config.conventions.rules = '.agent/rules';
            log('  ', '  ✓ Found .agent/rules/');
        }
        if (existsSync(agentsFile)) {
            config.conventions.agents = 'AGENTS.md';
            log('  ', '  ✓ Found AGENTS.md');
        }
    }

    // 3. Skills — scan apps/ for skill/agent files
    const appsDir = join(repoPath, 'apps');
    if (existsSync(appsDir)) {
        config.apps_dir = 'apps';
        const skills: Array<{ app: string; path: string }> = [];
        const appDirs = readdirSync(appsDir, { withFileTypes: true })
            .filter(d => d.isDirectory())
            .map(d => d.name);

        for (const appName of appDirs) {
            for (const filename of SKILL_FILENAMES) {
                const skillPath = join(appsDir, appName, filename);
                if (existsSync(skillPath)) {
                    const relPath = relative(repoPath, skillPath);
                    skills.push({ app: appName, path: relPath });
                    log('  ', `  ✓ Found ${relPath}`);
                }
            }
        }

        if (skills.length > 0) {
            config.skills = skills;
        }
    }

    // 4. Templates — look for apps/starter
    if (existsSync(join(repoPath, 'apps', 'starter'))) {
        config.templates = { starter: 'apps/starter' };
        log('  ', '  ✓ Found apps/starter template');
    }

    return config;
}

function guessRepoName(repoPath: string): string {
    // Try package.json
    const pkgPath = join(repoPath, 'package.json');
    if (existsSync(pkgPath)) {
        try {
            const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));
            if (pkg.name) return pkg.name;
        } catch { /* ignore */ }
    }
    // Fall back to directory name
    return repoPath.split('/').pop() || 'unknown';
}
