/**
 * Writer — writes generated files to the target repo and handles git operations.
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { execSync } from 'node:child_process';
import type { GeneratedFile, AppSpec, FeatureSpec, BuildResult, StackConfig } from './types.ts';
import { log, logError } from './log.ts';

/**
 * Write generated files to a target directory.
 * Creates directories as needed.
 */
export function writeFiles(targetDir: string, files: GeneratedFile[]): string[] {
    const writtenPaths: string[] = [];

    for (const file of files) {
        const absPath = resolve(targetDir, file.filename);
        const dir = dirname(absPath);

        if (!existsSync(dir)) {
            mkdirSync(dir, { recursive: true });
        }

        writeFileSync(absPath, file.content);
        writtenPaths.push(file.filename);
        log('  ', `  ✓ ${file.filename}`);
    }

    log('✓', `Wrote ${writtenPaths.length} files to ${targetDir}`);
    return writtenPaths;
}

/**
 * Run package install in the target directory.
 * Detects package manager from spec stack config.
 */
export function setupProject(targetDir: string, packageManager?: string): boolean {
    if (!existsSync(join(targetDir, 'package.json'))) {
        log('!', 'No package.json — skipping install');
        return false;
    }

    let cmd: string;
    switch (packageManager?.toLowerCase()) {
        case 'pnpm': cmd = 'pnpm install --no-frozen-lockfile'; break;
        case 'yarn': cmd = 'yarn install --no-immutable'; break;
        case 'bun': cmd = 'bun install'; break;
        default: cmd = 'npm install --legacy-peer-deps'; break;
    }

    try {
        log('●', `Running ${cmd} in ${targetDir}...`);
        execSync(cmd, { cwd: targetDir, stdio: 'pipe', timeout: 120_000 });
        log('✓', 'Package install complete');
        return true;
    } catch (error) {
        const msg = error instanceof Error ? error.message : String(error);
        logError(`Package install failed: ${msg.slice(0, 200)}`);
        return false;
    }
}

/**
 * Stage all changed files and commit.
 */
export function gitCommit(repoPath: string, message: string): boolean {
    try {
        // Init git repo if not present
        if (!existsSync(join(repoPath, '.git'))) {
            log('●', 'Initializing git repo');
            execSync('git init', { cwd: repoPath, stdio: 'pipe' });
            log('✓', 'Git repo initialized');
        }

        execSync('git add -A', { cwd: repoPath, stdio: 'pipe' });
        execSync(`git commit -m "${message}"`, { cwd: repoPath, stdio: 'pipe' });
        log('✓', `Committed: ${message}`);
        return true;
    } catch (error) {
        const msg = error instanceof Error ? error.message : String(error);
        // "nothing to commit" is not an error
        if (msg.includes('nothing to commit')) {
            log('!', 'Nothing to commit');
            return true;
        }
        logError(`Git commit failed: ${msg}`);
        return false;
    }
}

/**
 * Push to remote.
 */
export function gitPush(repoPath: string, branch?: string): boolean {
    try {
        if (!existsSync(join(repoPath, '.git'))) {
            log('!', 'Not a git repo — skipping push');
            return false;
        }

        const cmd = branch ? `git push origin ${branch}` : 'git push';
        execSync(cmd, { cwd: repoPath, stdio: 'pipe' });
        log('✓', 'Pushed to remote');
        return true;
    } catch (error) {
        const msg = error instanceof Error ? error.message : String(error);
        logError(`Git push failed: ${msg}`);
        return false;
    }
}

// ─── Knowledge Feedback ──────────────────────────────────

/**
 * Write a build summary into `.factory/knowledge/builds/` so future specs
 * have context about what has already been built.
 *
 * The context gatherer auto-discovers these if the directory is listed
 * in factory.yaml skills.files or if discovery is set to auto.
 */
export function writeKnowledgeEntry(
    repoPath: string,
    appName: string,
    result: BuildResult,
    stack: StackConfig,
    specFile: string,
): void {
    const knowledgeDir = join(repoPath, '.factory', 'knowledge', 'builds');
    if (!existsSync(knowledgeDir)) {
        mkdirSync(knowledgeDir, { recursive: true });
    }

    const slug = appName.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
    const filePath = join(knowledgeDir, `${slug}.md`);
    const timestamp = new Date().toISOString();
    const fileList = result.files.map(f => `- \`${f.filename}\``).join('\n');

    const content = `# ${appName}

> Auto-generated by Factory on ${timestamp}

## Summary

- **Spec**: \`${specFile}\`
- **Status**: ${result.success ? '✅ Successful' : '⚠️ Completed with errors'}
- **Files generated**: ${result.files.length}
- **Iterations**: ${result.iterations}
${result.errors?.length ? `- **Errors**: ${result.errors.join(', ')}` : ''}

## Stack

- **Framework**: ${stack.framework}
- **Package Manager**: ${stack.packageManager || 'npm'}
- **Language**: ${stack.language || 'TypeScript'}
${stack.linter ? `- **Linter**: ${stack.linter}` : ''}
${stack.testing ? `- **Testing**: ${stack.testing}` : ''}
${stack.database ? `- **Database**: ${stack.database}` : ''}

## Architecture

${result.plan?.architecture || 'No plan recorded.'}

## Key Decisions

${result.plan?.decisions?.map(d => `- ${d}`).join('\n') || 'No decisions recorded.'}

## Files

${fileList}
`;

    writeFileSync(filePath, content);
    log('✓', `Knowledge entry written: .factory/knowledge/builds/${slug}.md`);
}

// ─── AGENTS.md Generation ────────────────────────────────

/**
 * Generate an AGENTS.md file inside the built app directory.
 *
 * This file describes the app's stack, structure, and conventions
 * so that AI coding assistants (Copilot, Cursor, Gemini, etc.)
 * understand the project when working on it later.
 */
export function writeAppAgentsMd(
    targetDir: string,
    appName: string,
    stack: StackConfig,
    files: GeneratedFile[],
): void {
    const agentsPath = join(targetDir, 'AGENTS.md');

    // Group files by directory
    const dirs = new Map<string, string[]>();
    for (const f of files) {
        const parts = f.filename.split('/');
        const dir = parts.length > 1 ? parts.slice(0, -1).join('/') : '.';
        const existing = dirs.get(dir) || [];
        existing.push(parts[parts.length - 1]);
        dirs.set(dir, existing);
    }

    // Build the folder tree
    const tree = Array.from(dirs.entries())
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([dir, fileNames]) => {
            const indent = dir === '.' ? '' : '│   ';
            const dirLine = dir === '.' ? '.' : `├── ${dir}/`;
            const fileLines = fileNames.map(f => `${indent}├── ${f}`).join('\n');
            return `${dirLine}\n${fileLines}`;
        })
        .join('\n');

    const content = `# ${appName} — Agent Instructions

> Auto-generated by Factory. Update this file as the app evolves.

## Stack

| Layer | Technology |
|-------|-----------|
| Framework | ${stack.framework} |
| Language | ${stack.language || 'TypeScript'} |
| Package Manager | ${stack.packageManager || 'npm'} |
${stack.linter ? `| Linter | ${stack.linter} |\n` : ''}${stack.testing ? `| Testing | ${stack.testing} |\n` : ''}${stack.database ? `| Database | ${stack.database} |\n` : ''}${stack.cloud ? `| Cloud | ${stack.cloud} |\n` : ''}
## Project Structure

\`\`\`
${tree}
\`\`\`

## Conventions

- Run \`${stack.packageManager || 'npm'} install\` after cloning
${stack.linter ? `- Lint with \`${lintCmdForAgents(stack.linter)}\`` : ''}
${stack.testing ? `- Test with \`${testCmdForAgents(stack.testing)}\`` : ''}
- This project was scaffolded by the Factory engine — preserve its structure
- Follow existing patterns when adding new files

## Key Files

${files.slice(0, 15).map(f => `- \`${f.filename}\``).join('\n')}
${files.length > 15 ? `\n...and ${files.length - 15} more files` : ''}
`;

    writeFileSync(agentsPath, content);
    log('✓', `AGENTS.md written to ${targetDir}`);
}

function lintCmdForAgents(linter: string): string {
    const map: Record<string, string> = {
        'eslint': 'npx eslint .',
        'biome': 'npx @biomejs/biome check .',
        'oxlint': 'npx oxlint .',
        'prettier': 'npx prettier --check .',
    };
    return map[linter.toLowerCase()] || `npx ${linter}`;
}

function testCmdForAgents(testing: string): string {
    const map: Record<string, string> = {
        'vitest': 'npx vitest run',
        'jest': 'npx jest',
        'playwright': 'npx playwright test',
        'cypress': 'npx cypress run',
    };
    return map[testing.toLowerCase()] || `npx ${testing}`;
}
