/**
 * Report generator — produces a build report after scaffolding.
 */

import { resolve } from 'node:path';
import type { AppSpec, BuildReport, ValidationResult } from './types.ts';
import { specSlug, specPort, specRegion } from './types.ts';
import { PATHS, writeFile, timestamp, log } from './utils.ts';
import { listFiles } from './scaffold.ts';

/**
 * Generate a build report for a scaffolded app.
 *
 * @param spec - The parsed app spec
 * @param validation - Validation results
 * @returns The generated BuildReport
 */
export function generateReport(spec: AppSpec, validation: ValidationResult): BuildReport {
    const slug = specSlug(spec);
    const port = specPort(spec);
    const pkgManager = spec.stack.packageManager || 'pnpm';
    const outputDir = resolve(PATHS.output, slug);
    const patchDir = resolve(outputDir, 'patches');

    const filesGenerated = listFiles(outputDir).filter(f => !f.startsWith('patches/'));
    const patchesGenerated = listFiles(patchDir);

    const report: BuildReport = {
        spec: slug,
        slug,
        timestamp: timestamp(),
        filesGenerated,
        patchesGenerated,
        validation,
        nextSteps: [
            `Copy output/${slug}/ into your project at apps/${slug}/`,
            'Apply patches from patches/ directory (see patches/APPLY.md)',
            `${pkgManager} install in project root`,
            `${pkgManager} build`,
            'Create .env.local from .env.example',
            `${pkgManager} dev`,
        ],
    };

    // Write markdown report
    const md = formatReport(report, spec);
    const reportPath = resolve(PATHS.reports, `${slug}-${Date.now()}.md`);
    writeFile(reportPath, md);

    log('✓', `Report written to ${reportPath}`);

    return report;
}

/**
 * Format a build report as Markdown.
 */
function formatReport(report: BuildReport, spec: AppSpec): string {
    const slug = specSlug(spec);
    const port = specPort(spec);
    const region = specRegion(spec);
    const tables = spec.data?.tables || [];

    const validationLines = report.validation.checks
        .map(c => `| ${c.passed ? '✅' : '❌'} | ${c.name} | ${c.message} |`)
        .join('\n');

    return `# Build Report: ${spec.appName}

**Slug**: \`${slug}\`
**Generated**: ${report.timestamp}
**Status**: ${report.validation.passed ? '✅ All checks passed' : '❌ Some checks failed'}

---

## App Summary

| Property | Value |
|---|---|
| Name | ${spec.appName} |
| Slug | ${slug} |
| Framework | ${spec.stack.framework} |
| Port | ${port} |
| Region | ${region} |
| Database | ${spec.stack.database || 'none'} |
| UI | ${spec.frontend?.ui || 'none'} |
| Tables | ${tables.map(t => t.name).join(', ') || 'none'} |

---

## Validation Results

| Status | Check | Details |
|---|---|---|
${validationLines}

---

## Files Generated (${report.filesGenerated.length})

\`\`\`
${report.filesGenerated.join('\n')}
\`\`\`

## Patches Generated (${report.patchesGenerated.length})

\`\`\`
${report.patchesGenerated.join('\n')}
\`\`\`

---

## Next Steps

${report.nextSteps.map((s, i) => `${i + 1}. ${s}`).join('\n')}

---

*Generated by Factory engine*
`;
}
